spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: farmer-service
          uri: lb://FARMER-SERVICE
          predicates:
            - Path=/api/farmers/**

        - id: dealer-service
          uri: lb://DEALER-SERVICE
          predicates:
            - Path=/api/v1/dealers/**

        - id: crop-service
          uri: lb://CROP-SERVICE
          predicates:
            - Path=/api/crops/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
